# Copyright (c) 2025, Huawei Technologies Co., Ltd. All rights reserved.

from typing import Any

import torch
from torch.profiler import record_function
from torch.distributed.fsdp._fully_shard._fsdp_common import (
    TrainingState,
    compiled_autograd_enabled,
    _from_local_no_grad,
)
from torch.distributed.fsdp._fully_shard._fsdp_collectives import (
    foreach_all_gather_copy_out,
    foreach_reduce,
)
from torch.distributed.fsdp._fully_shard._fsdp_param import FSDPParam
from torch.distributed.fsdp._fully_shard._fsdp_param_group import (
    FSDPParamGroup as PyTorchFSDPParamGroup,
    AllReduceState,
    logger,
)

from fsdp_turbo.distributed.fine_grained_fully_shard.state import (
    AllGatherState,
    ReduceScatterState,
)


class FSDPParamGroup(PyTorchFSDPParamGroup):
    """
    FSDPTurbo Extended FSDP Parameter Group

    Compared to PyTorch's native FSDPParamGroup, the new features include:
    - hook_module: Supports associating hook modules
    - global_comm_ctx: Supports multiple communication contexts
    - Overrides wait_for_unshard and post_backward methods
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.reduce_scatter_reduce_op = None

    def wait_for_unshard(self):
        """
        Waits for preceding All-Gather operations to complete before unsharding.

        Specifically checks global_comm_ctx for events generated by DIFFERENT hook_modules.

        This enables overlapping communication: Layer N can start computing while layer N+1
        is still gathering, provided they use different streams/contexts.
        """

        if not self._all_gather_result:
            return  # no preceding unshard

        if self.mesh_info.shard_mesh_size == 1:
            for fsdp_param in self.fsdp_params:
                if not hasattr(fsdp_param, '_unsharded_param'):
                    unsharded_param = fsdp_param._sharded_local_tensor
                    if fsdp_param.is_dtensor:
                        unsharded_param = _from_local_no_grad(
                            unsharded_param, fsdp_param._tp_spec
                        )
                    fsdp_param._unsharded_param = unsharded_param
            self._to_unsharded()
            self._all_gather_result = None
            return

        async_op = self._all_gather_result.all_gather_work is not None
        if self._training_state == TrainingState.FORWARD:  # implicit prefetch
            for comm_ctx in self.global_comm_ctx:
                if prev_all_gather_state := comm_ctx.all_gather_state:
                    # Only wait if the previous operation belongs to a DIFFERENT hook_module.
                    # If it's the same module, dependencies are handled differently or sequentially.
                    # Note: Logic assumes self.hook_module is available on the param group
                    if prev_all_gather_state.hook_module != self.hook_module:
                        self._wait_all_gather_streams_on_event(prev_all_gather_state.event)
                        comm_ctx.all_gather_state = None  # free the all-gather result

        with record_function(self._with_fqn("FSDP::all_gather_copy_out")):
            foreach_all_gather_copy_out(
                self._all_gather_result,
                self.fsdp_params,
                self._all_gather_process_group,
            )
        for fsdp_param in self.fsdp_params:
            fsdp_param.init_unsharded_param()
        self._to_unsharded()
        all_gather_copy_out_event = self.device_handle.Event()
        all_gather_copy_out_event.record()
        if not async_op and self._training_state == TrainingState.FORWARD:
            # Defer free to allow for overlap of this copy-out with next
            # all-gather collective
            self.comm_ctx.all_gather_state = AllGatherState(
                self._all_gather_result, all_gather_copy_out_event, self.hook_module
            )
        else:
            self._wait_all_gather_streams_on_event(all_gather_copy_out_event)
        self._all_gather_result = None  # free unless saved in `all_gather_state`
    
    def post_backward(self, *unused: Any):
        """
        Custom post-backward logic for gradient reduction and resharding.

        Ensures that the current stream waits for Reduce-Scatter events from
        OTHER communication contexts (different hook_modules) before starting
        its own reduction. This maintains correctness in multi-stream setups.
        """

        if not compiled_autograd_enabled():
            logger.debug("%s", self._with_fqn("FSDP::post_backward"))
        self._training_state = TrainingState.POST_BACKWARD
        with record_function(self._with_fqn("FSDP::post_backward_accumulate")):
            for fsdp_param in self.fsdp_params:
                fsdp_param.accumulate_unsharded_grad_if_needed()
        with record_function(self._with_fqn("FSDP::post_backward_reshard")):
            if not self.reduce_grads:
                if self.reshard_after_backward:
                    self.reshard()
                for fsdp_param in self.fsdp_params:
                    fsdp_param.to_accumulated_grad_if_needed()
                return
            # Save the autograd-computed gradients before resharding to only
            # access the unsharded parameters when their data is present
            fsdp_params_with_grad: list[FSDPParam] = []
            unsharded_grads: list[torch.Tensor] = []
            for fsdp_param in self.fsdp_params:
                if not hasattr(fsdp_param, "_unsharded_param"):
                    continue
                # May have an accumulated gradient of the reduce dtype if the
                # previous backward did not reduce-scatter
                if fsdp_param.unsharded_accumulated_grad is not None:
                    fsdp_params_with_grad.append(fsdp_param)
                    unsharded_grads.append(fsdp_param.unsharded_accumulated_grad_data)
                    fsdp_param.unsharded_accumulated_grad = None
                elif fsdp_param.unsharded_param.grad is not None:
                    fsdp_params_with_grad.append(fsdp_param)
                    unsharded_grads.append(fsdp_param.unsharded_grad_data)
                    fsdp_param.unsharded_param.grad = None
            if self.reshard_after_backward:
                self.reshard()
        if len(fsdp_params_with_grad) == 0:
            return
        with record_function(self._with_fqn("FSDP::post_backward_reduce")):
            # Wait for local context reduce-scatter
            if self.comm_ctx.reduce_scatter_state is not None:
                self.device_handle.current_stream().wait_event(
                    self.comm_ctx.reduce_scatter_state.event
                )
                self.comm_ctx.reduce_scatter_state = None

            # Wait for GLOBAL context reduce-scatters from DIFFERENT hook modules
            for comm_ctx in self.global_comm_ctx:
                if comm_ctx.reduce_scatter_state and comm_ctx.reduce_scatter_state.hook_module != self.hook_module:
                    self.device_handle.current_stream().wait_event(comm_ctx.reduce_scatter_state.event)
                    comm_ctx.reduce_scatter_state = None

            all_reduce_pg = self._all_reduce_process_group if self._is_hsdp else None
            all_reduce_stream: torch.cuda.Stream
            if all_reduce_pg is None and self._all_reduce_hook_stream is not None:
                # this means the native HSDP is not enabled,
                # but user may want to have a custom HSDP setup
                if self._all_reduce_hook is None:
                    raise AssertionError(
                        "all reduce hook stream is specified but hook itself is missing."
                    )
                all_reduce_stream = self._all_reduce_hook_stream
            else:
                all_reduce_stream = self.comm_ctx.all_reduce_stream

            self._wait_for_post_backward()
            (
                reduce_scatter_input,
                reduce_scatter_event,
                self._post_reduce_event,
                all_reduce_input,
                all_reduce_event,
                self._partial_reduce_output,
            ) = foreach_reduce(
                fsdp_params_with_grad,
                unsharded_grads,
                self._reduce_scatter_process_group,
                self.comm_ctx.reduce_scatter_stream,
                self._reduce_scatter_comm,
                self._orig_dtype,
                self._reduce_dtype,
                self.device,
                self.reduce_scatter_reduce_op,
                self._all_reduce_process_group if self._is_hsdp else None,
                all_reduce_stream,
                self.all_reduce_grads,
                self._partial_reduce_output,
                self._all_reduce_hook,
            )
            self.comm_ctx.reduce_scatter_state = ReduceScatterState(
                reduce_scatter_input, reduce_scatter_event, self.hook_module
            )
            if all_reduce_input is not None:
                if all_reduce_event is None:
                    raise AssertionError("all_reduce_event cannot be None.")
                self._all_reduce_state = AllReduceState(
                    all_reduce_input, all_reduce_event
                )
